# Build stage
FROM golang:1.26.3-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags="-w -s" -o bin/worker ./cmd/worker

# Run stage
FROM alpine:3.19

RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=builder /app/bin/worker /app/worker

ENTRYPOINT ["/app/worker"]
