// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/worker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	PodIp         string                 `protobuf:"bytes,3,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *WorkerInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *WorkerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TestPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PlanJson      []byte                 `protobuf:"bytes,2,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`           // JSON-encoded TestPlan struct
	WorkerIndex   int32                  `protobuf:"varint,3,opt,name=worker_index,json=workerIndex,proto3" json:"worker_index,omitempty"` // which shard of virtual users this worker owns
	TotalWorkers  int32                  `protobuf:"varint,4,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPlanResponse) Reset() {
	*x = TestPlanResponse{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPlanResponse) ProtoMessage() {}

func (x *TestPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPlanResponse.ProtoReflect.Descriptor instead.
func (*TestPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *TestPlanResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TestPlanResponse) GetPlanJson() []byte {
	if x != nil {
		return x.PlanJson
	}
	return nil
}

func (x *TestPlanResponse) GetWorkerIndex() int32 {
	if x != nil {
		return x.WorkerIndex
	}
	return 0
}

func (x *TestPlanResponse) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Stats         *WorkerStats           `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *HeartbeatRequest) GetStats() *WorkerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type WorkerStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActiveGoroutines int64                  `protobuf:"varint,1,opt,name=active_goroutines,json=activeGoroutines,proto3" json:"active_goroutines,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes      int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	RequestsPerSec   float64                `protobuf:"fixed64,4,opt,name=requests_per_sec,json=requestsPerSec,proto3" json:"requests_per_sec,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,5,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors      int64                  `protobuf:"varint,6,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkerStats) Reset() {
	*x = WorkerStats{}
	mi := &file_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStats) ProtoMessage() {}

func (x *WorkerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStats.ProtoReflect.Descriptor instead.
func (*WorkerStats) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerStats) GetActiveGoroutines() int64 {
	if x != nil {
		return x.ActiveGoroutines
	}
	return 0
}

func (x *WorkerStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *WorkerStats) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *WorkerStats) GetRequestsPerSec() float64 {
	if x != nil {
		return x.RequestsPerSec
	}
	return 0
}

func (x *WorkerStats) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *WorkerStats) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        string                 `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`                              // CONTINUE | STOP | SCALE_DOWN
	NewVuCount    int32                  `protobuf:"varint,2,opt,name=new_vu_count,json=newVuCount,proto3" json:"new_vu_count,omitempty"` // if SCALE_DOWN: new target VU count for this worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *HeartbeatResponse) GetNewVuCount() int32 {
	if x != nil {
		return x.NewVuCount
	}
	return 0
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Graceful      bool                   `protobuf:"varint,3,opt,name=graceful,proto3" json:"graceful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *StopRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StopRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *StopRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type StopResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DrainedRequests int64                  `protobuf:"varint,2,opt,name=drained_requests,json=drainedRequests,proto3" json:"drained_requests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *StopResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *StopResponse) GetDrainedRequests() int64 {
	if x != nil {
		return x.DrainedRequests
	}
	return 0
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\x13loadforge.worker.v1\"\x8e\x01\n" +
	"\n" +
	"WorkerInfo\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06pod_ip\x18\x03 \x01(\tR\x05podIp\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x8e\x01\n" +
	"\x10TestPlanResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tplan_json\x18\x02 \x01(\fR\bplanJson\x12!\n" +
	"\fworker_index\x18\x03 \x01(\x05R\vworkerIndex\x12#\n" +
	"\rtotal_workers\x18\x04 \x01(\x05R\ftotalWorkers\"\xa1\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x126\n" +
	"\x05stats\x18\x04 \x01(\v2 .loadforge.worker.v1.WorkerStatsR\x05stats\"\xf2\x01\n" +
	"\vWorkerStats\x12+\n" +
	"\x11active_goroutines\x18\x01 \x01(\x03R\x10activeGoroutines\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12(\n" +
	"\x10requests_per_sec\x18\x04 \x01(\x01R\x0erequestsPerSec\x12%\n" +
	"\x0etotal_requests\x18\x05 \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x06 \x01(\x03R\vtotalErrors\"M\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\tR\x06signal\x12 \n" +
	"\fnew_vu_count\x18\x02 \x01(\x05R\n" +
	"newVuCount\"]\n" +
	"\vStopRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bgraceful\x18\x03 \x01(\bR\bgraceful\"]\n" +
	"\fStopResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10drained_requests\x18\x02 \x01(\x03R\x0fdrainedRequests2\x90\x02\n" +
	"\rWorkerControl\x12R\n" +
	"\bRegister\x12\x1f.loadforge.worker.v1.WorkerInfo\x1a%.loadforge.worker.v1.TestPlanResponse\x12^\n" +
	"\tHeartbeat\x12%.loadforge.worker.v1.HeartbeatRequest\x1a&.loadforge.worker.v1.HeartbeatResponse(\x010\x01\x12K\n" +
	"\x04Stop\x12 .loadforge.worker.v1.StopRequest\x1a!.loadforge.worker.v1.StopResponseB6Z4github.com/vatsalchaudhary/loadforge/proto/worker/v1b\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_worker_proto_goTypes = []any{
	(*WorkerInfo)(nil),        // 0: loadforge.worker.v1.WorkerInfo
	(*TestPlanResponse)(nil),  // 1: loadforge.worker.v1.TestPlanResponse
	(*HeartbeatRequest)(nil),  // 2: loadforge.worker.v1.HeartbeatRequest
	(*WorkerStats)(nil),       // 3: loadforge.worker.v1.WorkerStats
	(*HeartbeatResponse)(nil), // 4: loadforge.worker.v1.HeartbeatResponse
	(*StopRequest)(nil),       // 5: loadforge.worker.v1.StopRequest
	(*StopResponse)(nil),      // 6: loadforge.worker.v1.StopResponse
}
var file_proto_worker_proto_depIdxs = []int32{
	3, // 0: loadforge.worker.v1.HeartbeatRequest.stats:type_name -> loadforge.worker.v1.WorkerStats
	0, // 1: loadforge.worker.v1.WorkerControl.Register:input_type -> loadforge.worker.v1.WorkerInfo
	2, // 2: loadforge.worker.v1.WorkerControl.Heartbeat:input_type -> loadforge.worker.v1.HeartbeatRequest
	5, // 3: loadforge.worker.v1.WorkerControl.Stop:input_type -> loadforge.worker.v1.StopRequest
	1, // 4: loadforge.worker.v1.WorkerControl.Register:output_type -> loadforge.worker.v1.TestPlanResponse
	4, // 5: loadforge.worker.v1.WorkerControl.Heartbeat:output_type -> loadforge.worker.v1.HeartbeatResponse
	6, // 6: loadforge.worker.v1.WorkerControl.Stop:output_type -> loadforge.worker.v1.StopResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
